language: php

php:
  - 5.4
  - 5.5

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer --dev install

script:
  - ant up
  - ant phpunit